import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/navbar'
import { QueryProvider } from '@/components/providers/query-provider'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Toaster } from 'sonner'
import { cn } from '@/lib/utils'

const font = Poppins({
  subsets: ["latin"],
  weight: ["500"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn(
          font.className,
        )}>
            <QueryProvider>
              <Toaster />
              <Navbar />
              {children}
            </QueryProvider>
        </body>
      </html>
    </SessionProvider>
  )
}
